services:
  # 1. 数据库服务（通过 ENABLE_MYSQL 控制，默认启用）
  db:
    image: swr.cn-north-4.myhuaweicloud.com/library/mysql:8.0
    container_name: my_mysql
    profiles:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}           # 数据库密码
      MYSQL_DATABASE: mydb                # 自动创建一个库
      # MYSQL_USER: user_ds                 # admin用户
      # MYSQL_PASSWORD: ds@888              # 用户密码
    ports:
      - "3306:3306" # 映射端口，方便你用 Navicat 连接
    volumes:
      - ./mysql_data:/var/lib/mysql # 数据持久化
    networks:
      - my_net

  # 2. Nginx 服务
  nginx:
    image: swr.cn-north-4.myhuaweicloud.com/library/nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web_data:/usr/share/nginx/web:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - app
    networks:
      - my_net

  # 3. Go 支付服务
  pay:
    image: ${PAY_IMAGE}
    container_name: my_go_pay
    ports:
      - "9090:9090"
    environment:
      - PAY_MODE=${PAY_MODE:-mock}
      - CPP_HOST=http://my_cpp_dev:8080
      - MOCK_ORDER_STATE=${MOCK_ORDER_STATE:-NOTPAY}
      - WECHAT_APPID=${WECHAT_APPID}
      - WECHAT_MCH_ID=${WECHAT_MCH_ID}
      - WECHAT_SERIAL_NO=${WECHAT_SERIAL_NO}
      - WECHAT_API_V3_KEY=${WECHAT_API_V3_KEY}
      - WECHAT_CERT_PATH=${WECHAT_CERT_PATH:-/app/certs}
      - WECHAT_NOTIFY_URL=${WECHAT_NOTIFY_URL}
    networks:
      - my_net
    volumes:
      - ./certs:/app/certs:ro 
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  # 4. 你的 C++ 应用（代码已在镜像构建时编译好）
  app:
    image: ${APP_IMAGE}
    container_name: my_cpp_dev
    ports:
      - "8080:8080"
    environment:
      - ENABLE_INIT_DB=${ENABLE_INIT_DB:-true}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - OSS_ENDPOINT=${OSS_ENDPOINT}
      - OSS_ACCESS_KEY_ID=${OSS_ACCESS_KEY_ID}
      - OSS_ACCESS_KEY_SECRET=${OSS_ACCESS_KEY_SECRET}
      - OSS_BUCKET_NAME=${OSS_BUCKET_NAME}
      - PAY_HOST=http://my_go_pay:9090
      - ENABLE_ORDER_CHECK=${ENABLE_ORDER_CHECK:-true}
      - ORDER_PAYMENT_TIMEOUT_MINUTES=${ORDER_PAYMENT_TIMEOUT_MINUTES:-30}
      - ORDER_CHECK_INTERVAL_SECONDS=${ORDER_CHECK_INTERVAL_SECONDS:-300}
    depends_on:
      - pay
    networks:
      - my_net
    privileged: true
    volumes:
      - web_data:/app/code/webSource
      - /etc/localtime:/etc/localtime:ro  # 同步宿主机时区
      - /etc/timezone:/etc/timezone:ro    # 同步宿主机时区

networks:
  my_net:
    driver: bridge

volumes:
  web_data: